#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT_DIR="${ROOT}/cicd-bootstrap"
OUT_FILE="${OUT_DIR}/terraform.tfvars"

prompt() {
  local var_name="$1"
  local msg="$2"
  local default="${3:-}"
  local value=""

  if [[ -n "${default}" ]]; then
    read -r -p "${msg} [${default}]: " value
    value="${value:-$default}"
  else
    read -r -p "${msg}: " value
  fi

  value="$(echo -n "$value" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
  if [[ -z "$value" ]]; then
    echo "Error: '${var_name}' cannot be empty." >&2
    exit 1
  fi
  printf '%s' "$value"
}

parse_github_url() {
  local url="$1"
  if [[ "$url" =~ github\.com[:/]+([^/]+)/([^/.]+)(\.git)?$ ]]; then
    GITHUB_OWNER="${BASH_REMATCH[1]}"
    GITHUB_REPO="${BASH_REMATCH[2]}"
    return 0
  fi

  echo "Error: couldn't parse GitHub repo URL: $url" >&2
  echo "Expected like: https://github.com/OWNER/REPO or git@github.com:OWNER/REPO.git" >&2
  exit 1
}

mkdir -p "$OUT_DIR"

echo "CI/CD bootstrap configuration"
echo "Generating ${OUT_FILE}"
echo

REPO_URL="$(prompt github_repo_url "GitHub repo URL (https://github.com/OWNER/REPO or git@github.com:OWNER/REPO.git)")"
parse_github_url "$REPO_URL"

AWS_REGION="$(prompt aws_region "AWS region" "us-east-1")"

cat > "$OUT_FILE" <<EOF
# Generated by first-run-cicd-setup.sh
# This file is local-only and should not be committed.

github_owner    = "${GITHUB_OWNER}"
github_repo     = "${GITHUB_REPO}"

aws_region      = "${AWS_REGION}"
EOF

echo
echo "==> Applying bootstrap (remote backend foundation: S3 + DynamoDB)..."
terraform -chdir=bootstrap init
terraform -chdir=bootstrap apply

echo "pulling outputs..."

terraform -chdir=bootstrap output -raw tfstate_bucket >/dev/null 2>&1 || {
  echo "ERROR: bootstrap output 'tfstate_bucket' missing."
  exit 1
}

echo "writing backend.env..."

cat > backend.env <<EOF
TFSTATE_BUCKET=$(terraform -chdir=bootstrap output -raw tfstate_bucket)
LOCK_TABLE=$(terraform -chdir=bootstrap output -raw lock_table)
AWS_REGION=$(terraform -chdir=bootstrap output -raw aws_region 2>/dev/null || echo us-east-1)
TFSTATE_KEY=terraform.tfstate
EOF

echo
echo "Done."
echo "Wrote: ${OUT_FILE}"
echo
echo "Next steps:"
echo "  terraform -chdir=cicd-bootstrap init"
echo "  terraform -chdir=cicd-bootstrap apply"

read -r -p "Run these steps now? [y/n]: " RESP
RESP="${RESP,,}"   # lowercase

if [[ "$RESP" == "y" || "$RESP" == "yes" ]]; then
  echo "Running next steps..."

  terraform -chdir=cicd-bootstrap init
  terraform -chdir=cicd-bootstrap apply --auto-approve
fi

echo
echo "Optional: create GitHub repo variables (requires GitHub CLI 'gh')."
echo "If you don't do this here, create them manually in GitHub:"
echo "  Settings → Secrets and variables → Actions → Variables"
echo
echo "  Install GitHub CLI (WSL/Ubuntu):"
echo "    sudo apt update && sudo apt install gh -y"
echo
echo "  Authenticate:"
echo "    gh auth login"
echo
echo "After running the CI/CD bootstrap, set these variables:"
echo

echo "  # AWS region used by GitHub Actions"
echo "  gh variable set AWS_REGION \\"
echo "    --repo ${GITHUB_OWNER}/${GITHUB_REPO} \\"
echo "    --body \"${AWS_REGION}\""
echo

echo "  # Preferred: store the FULL GitHub Actions OIDC role ARN"
echo "  gh variable set ACTIONS_OIDC_ROLE_ARN \\"
echo "    --repo ${GITHUB_OWNER}/${GITHUB_REPO} \\"
echo "    --body \"\$(terraform -chdir=cicd-bootstrap output -raw aws_role_arn)\""
echo
echo "  gh variable set TFSTATE_BUCKET \\"
echo "    --repo ${GITHUB_OWNER}/${GITHUB_REPO} \\"
echo "    --body \"$(terraform -chdir=bootstrap output -raw tfstate_bucket)\""
echo

echo "  gh variable set LOCK_TABLE \\"
echo "    --repo ${GITHUB_OWNER}/${GITHUB_REPO} \\"
echo "    --body \"$(terraform -chdir=bootstrap output -raw lock_table)\""
echo

echo "  gh variable set TFSTATE_KEY \\"
echo "    --repo ${GITHUB_OWNER}/${GITHUB_REPO} \\"
echo "    --body \"terraform.tfstate\""
echo

read -r -p "Run these gh variable steps now? [y/n]: " RESP2
RESP2="${RESP2,,}"   # lowercase

if [[ "$RESP2" == "y" || "$RESP2" == "yes" ]]; then
  if ! gh auth status >/dev/null 2>&1; then
    echo "GitHub CLI not authenticated. Launching login..."
    gh auth login || { echo "GitHub auth aborted. Skipping gh variable setup, this must now be done manually or re-run script."; exit 1; }
  fi

  echo "Running var registration..."

  gh variable set AWS_REGION \
    --repo "${GITHUB_OWNER}/${GITHUB_REPO}" \
    --body "${AWS_REGION}"

  gh variable set ACTIONS_OIDC_ROLE_ARN \
    --repo "${GITHUB_OWNER}/${GITHUB_REPO}" \
    --body "$(terraform -chdir=bootstrap output -raw aws_role_arn)"

  gh variable set TFSTATE_BUCKET \
    --repo "${GITHUB_OWNER}/${GITHUB_REPO}" \
    --body "$(terraform -chdir=bootstrap output -raw tfstate_bucket)"

  gh variable set LOCK_TABLE \
    --repo "${GITHUB_OWNER}/${GITHUB_REPO}" \
    --body "$(terraform -chdir=bootstrap output -raw lock_table)"

  gh variable set TFSTATE_KEY \
    --repo "${GITHUB_OWNER}/${GITHUB_REPO}" \
    --body "terraform.tfstate"

fi

echo "Once these variables are set, GitHub Actions is fully enabled."
echo "CI/CD workflows will assume the role via OIDC with no static AWS credentials."
